"""Build small, attributed tour polygons (requires pyshp and shapely).

Historical envelopes are editorial approximations, not digitized ancient borders.
Modern Natural Earth land only trims coastlines; country borders are dissolved.
HydroBASINS is a measured catchment, retained separately from those envelopes.
Input download URLs and attribution: dist/territory-tours-sources.md.
"""
import json
from pathlib import Path
import shapefile
from shapely.geometry import shape, Polygon, MultiPolygon, mapping
from shapely.ops import unary_union

ROOT = Path(__file__).resolve().parents[1]
land = unary_union([shape(s.__geo_interface__) for s in shapefile.Reader(
    str(ROOT / 'data/countries/ne_50m_admin_0_countries')).shapes()])
envelopes = json.loads((ROOT / 'scripts/tour-area-envelopes.json').read_text())
output = {}

def geometry(g, tolerance):
    g = g.simplify(tolerance, preserve_topology=True)
    polys = list(g.geoms) if g.geom_type == 'MultiPolygon' else [g]
    # Tiny offshore fragments have no useful screen footprint at tour scale.
    return mapping(MultiPolygon([p for p in polys if p.area > .003]))

for key, spec in envelopes.items():
    envelope = unary_union([Polygon(r) for r in spec['rings']])
    assert envelope.is_valid, key
    output[key] = [{k: v for k, v in spec.items() if k != 'rings'} | {
        'kind': 'empire', 'approximate': True,
        'geometry': geometry(envelope.intersection(land), .025)}]

reader = shapefile.Reader(str(ROOT / 'data/tour-areas/hybas_sa_lev03_v1c'))
amazon = next(s for s in reader.iterShapeRecords() if s.record.as_dict()['HYBAS_ID'] == 6030007000)
output['amazon-mouth'] = [{
    'id': 'amazon-basin', 'title': 'Amazon drainage basin', 'kind': 'basin',
    'source': 'https://www.hydrosheds.org/products/hydrobasins',
    'dataset': 'HydroBASINS v1c, South America, level 03', 'hybasId': 6030007000,
    'sourceAreaKm2': amazon.record.as_dict()['SUB_AREA'],
    'attribution': 'HydroSHEDS / WWF; Lehner & Grill (2013), doi:10.1002/hyp.9740',
    'geometry': geometry(shape(amazon.shape.__geo_interface__), .018)}]

def rounded(v):
    if isinstance(v, dict): return {k: rounded(x) for k, x in v.items()}
    if isinstance(v, (list, tuple)): return [rounded(x) for x in v]
    return round(v, 5) if isinstance(v, float) else v

target = ROOT / 'dist/tour-area-data.mjs'
target.write_text('// Generated by scripts/build-tour-areas.py. See territory-tours-sources.md for provenance.\n'
                  + 'export const tourAreaSets=' + json.dumps(rounded(output), separators=(',', ':'), ensure_ascii=False) + ';\n')
print(f'Wrote {target.name}: {target.stat().st_size:,} bytes; five area tours.')
